# Site settings
title: Corrupting the Youth
header-img: img/death-of-socrates-original.jpg
email: 
copyright_name: Matt Cleaver
description: "Teaching Philosophy - Thoughts & Resources"
baseurl: ""
url: "http://www.corruptingtheyouth.com"
twitter_username: mattcleaver
github_username:  
facebook_username:  
email_username:  

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
    
